
import { Employee } from './types';

export const RAW_DATA: Employee[] = [
  { id: "3414463", nombre: "ESCOBAR TABORDA WILMAR ANDRES", cargo: "ALMACENISTA", fechaDescanso: "Vacaciones", ubicacion: "Bodega" },
  { id: "1100689417", nombre: "RICARDO VEGA JHON JAVIER", cargo: "AUXILIAR ALMACENISTA", fechaDescanso: "Vacaciones", ubicacion: "Bodega" },
  { id: "8111877", nombre: "HIGUITA MEJIA FABIO ALONSO", cargo: "ENCARGADO(A)", fechaDescanso: "26 de diciembre de 2025", ubicacion: "Altos de la virgen" },
  { id: "15341611", nombre: "GARCIA GARCIA WILSON DE JESUS", cargo: "AYUDANTE", fechaDescanso: "26 de diciembre de 2025", ubicacion: "Altos de la virgen" },
  { id: "71794428", nombre: "BORJA FRANCO HERMIN ALONSO", cargo: "AYUDANTE", fechaDescanso: "26 de diciembre de 2025", ubicacion: "Altos de la virgen" },
  { id: "98543058", nombre: "CANO OSPINA GILDARDO DE JESUS", cargo: "AYUDANTE", fechaDescanso: "26 de diciembre de 2025", ubicacion: "Altos de la virgen" },
  { id: "98614185", nombre: "TORRES EMILSON", cargo: "AYUDANTE", fechaDescanso: "26 de diciembre de 2025", ubicacion: "Altos de la virgen" },
  { id: "1000203413", nombre: "HERRERA GONZALEZ HAROLD", cargo: "AYUDANTE", fechaDescanso: "26 de diciembre de 2025", ubicacion: "Altos de la virgen" },
  { id: "1000207973", nombre: "TORRES CADAVID ESTIVEN", cargo: "AYUDANTE", fechaDescanso: "26 de diciembre de 2025", ubicacion: "Altos de la virgen" },
  { id: "1003252160", nombre: "MISATH PALOMINO VICTOR ANTONIO", cargo: "AYUDANTE", fechaDescanso: "26 de diciembre de 2025", ubicacion: "Altos de la virgen" },
  { id: "1025641962", nombre: "MURILLO MADRIGAL FERNEY DARIO", cargo: "AYUDANTE", fechaDescanso: "26 de diciembre de 2025", ubicacion: "Altos de la virgen" },
  { id: "1036629704", nombre: "BETANCUR USUGA DEIMER EULICE", cargo: "AYUDANTE", fechaDescanso: "26 de diciembre de 2025", ubicacion: "Altos de la virgen" },
  { id: "1039421436", nombre: "RODAS PIEDRAHITA MANUEL SALVADOR", cargo: "OFICIAL", fechaDescanso: "26 de diciembre de 2025", ubicacion: "Altos de la virgen" },
  { id: "1152220314", nombre: "RAMOS RAMOS JORGE LUIS", cargo: "AYUDANTE", fechaDescanso: "26 de diciembre de 2025", ubicacion: "Altos de la virgen" },
  { id: "1152456684", nombre: "PATERNINA LONDOÑO YERMI ENRIQUE", cargo: "AYUDANTE", fechaDescanso: "26 de diciembre de 2025", ubicacion: "Altos de la virgen" },
  { id: "8321372", nombre: "QUINTERO QUINTERO JUAN HERNEY", cargo: "ENCARGADO(A)", fechaDescanso: "2 de enero de 2026", ubicacion: "Altos de la virgen" },
  { id: "11645225", nombre: "PALACIOS MOSQUERA JACKSON ARIEL", cargo: "OFICIAL", fechaDescanso: "2 de enero de 2026", ubicacion: "Altos de la virgen" },
  { id: "18606950", nombre: "CAÑAVERAL MARULANDA CRISTOBAL ANTONIO", cargo: "OFICIAL", fechaDescanso: "2 de enero de 2026", ubicacion: "Altos de la virgen" },
  { id: "78026446", nombre: "GUZMAN ALMANZA CARMELO MIGUEL", cargo: "AYUDANTE", fechaDescanso: "2 de enero de 2026", ubicacion: "Altos de la virgen" },
  { id: "1000396991", nombre: "BEDOYA PINO JUAN ANDRES", cargo: "AYUDANTE", fechaDescanso: "2 de enero de 2026", ubicacion: "Altos de la virgen" },
  { id: "1066512701", nombre: "ZABALA RODRIGUEZ CESAR AUGUSTO", cargo: "OFICIAL PEGADOR", fechaDescanso: "2 de enero de 2026", ubicacion: "Altos de la virgen" },
  { id: "1070807913", nombre: "PALENCIA RAMOS JOSE DAVID", cargo: "AYUDANTE", fechaDescanso: "2 de enero de 2026", ubicacion: "Altos de la virgen" },
  { id: "1077474328", nombre: "LOPEZ PADILLA WEINER ALBERTO", cargo: "AYUDANTE", fechaDescanso: "2 de enero de 2026", ubicacion: "Altos de la virgen" },
  { id: "1128414892", nombre: "ARTEAGA OSPINA ERIKA TATIANA", cargo: "AUXILIAR DE TRANSITO", fechaDescanso: "2 de enero de 2026", ubicacion: "Altos de la virgen" },
  { id: "82331511", nombre: "OVIEDO ORTEGA RAUL ENRIQUE", cargo: "AYUDANTE", fechaDescanso: "2 de enero de 2026", ubicacion: "Altos de la virgen" },
  { id: "3271414", nombre: "PEÑA RAFAEL ORANGEL", cargo: "AYUDANTE", fechaDescanso: "No sale", ubicacion: "Altos de la virgen" },
  { id: "4909459", nombre: "LOPEZ PEREZ ESKAR SAMUEL", cargo: "AUXILIAR ALMACENISTA BODEGA", fechaDescanso: "No sale", ubicacion: "Altos de la virgen" },
  { id: "5856243", nombre: "ALVARADO SANCHEZ HECTOR RICARDO", cargo: "AYUDANTE", fechaDescanso: "No sale", ubicacion: "Altos de la virgen" },
  { id: "1001235341", nombre: "PULGARIN CARTAGENA SANTIAGO ANDRES", cargo: "CONDUCTOR - OPERADOR DE MAQUINARIA", fechaDescanso: "No sale", ubicacion: "Altos de la virgen" },
  { id: "1037263255", nombre: "VELEZ PANTOJA NORMAN ARTURO", cargo: "AYUDANTE", fechaDescanso: "No sale", ubicacion: "Altos de la virgen" },
  { id: "1042707049", nombre: "BEJARANO MOSQUERA GUSTAVO ADOLFO", cargo: "AYUDANTE", fechaDescanso: "No sale", ubicacion: "Altos de la virgen" },
  { id: "3483186", nombre: "MAJORE DOMICO EMILIANO", cargo: "AYUDANTE", fechaDescanso: "26 de diciembre de 2025", ubicacion: "Blanquizal" },
  { id: "10967046", nombre: "HERRERA PINTO DAVID FERNANDO", cargo: "OFICIAL", fechaDescanso: "26 de diciembre de 2025", ubicacion: "Blanquizal" },
  { id: "1000189265", nombre: "ARIAS QUIRAMA JUAN DAVID", cargo: "AYUDANTE", fechaDescanso: "26 de diciembre de 2025", ubicacion: "Blanquizal" },
  { id: "1040761263", nombre: "MARTINEZ CUESTA ELIAS", cargo: "AYUDANTE", fechaDescanso: "26 de diciembre de 2025", ubicacion: "Blanquizal" },
  { id: "1055836598", nombre: "LOPEZ CANDAMIL ARIEL", cargo: "AYUDANTE", fechaDescanso: "26 de diciembre de 2025", ubicacion: "Blanquizal" },
  { id: "1076018596", nombre: "PALACIOS PEREA NEIDER", cargo: "AYUDANTE", fechaDescanso: "26 de diciembre de 2025", ubicacion: "Blanquizal" },
  { id: "1128430873", nombre: "GARCIA ESPINOSA HANDER YOSIMI", cargo: "OFICIAL", fechaDescanso: "26 de diciembre de 2025", ubicacion: "Blanquizal" },
  { id: "1214736880", nombre: "NOREÑA TABORDA DUBER STIVEN", cargo: "AYUDANTE", fechaDescanso: "Vacaciones", ubicacion: "Blanquizal" },
  { id: "98694921", nombre: "ARBELAEZ QUINCHIA HERNAN DARIO", cargo: "AYUDANTE", fechaDescanso: "2 de enero de 2026", ubicacion: "Altos de la virgen" },
  { id: "5042458", nombre: "BRACHO GIOVANNY JOSE", cargo: "AYUDANTE", fechaDescanso: "2 de enero de 2026", ubicacion: "Blanquizal" },
  { id: "71745913", nombre: "RENDON RUA DIEGO ALBERTO", cargo: "OFICIAL", fechaDescanso: "2 de enero de 2026", ubicacion: "Blanquizal" },
  { id: "1001035005", nombre: "VANEGAS USUGA YEFERSON ALBERTO", cargo: "AYUDANTE", fechaDescanso: "2 de enero de 2026", ubicacion: "Blanquizal" },
  { id: "1001596724", nombre: "FAJARDO CROSS YAN CARLOS", cargo: "AYUDANTE", fechaDescanso: "2 de enero de 2026", ubicacion: "Blanquizal" },
  { id: "1017258062", nombre: "QUEJADA SANTOS ALCIDES", cargo: "AYUDANTE", fechaDescanso: "2 de enero de 2026", ubicacion: "Blanquizal" },
  { id: "1038114225", nombre: "PADILLA SEVERICHE FRANCOLLI", cargo: "OFICIAL", fechaDescanso: "2 de enero de 2026", ubicacion: "Blanquizal" },
  { id: "1045503693", nombre: "DIAZ RAMOS MARLON DAVID", cargo: "AYUDANTE", fechaDescanso: "2 de enero de 2026", ubicacion: "Blanquizal" },
  { id: "1129498548", nombre: "USUGA CORDOBA DANIEL DAVID", cargo: "AYUDANTE", fechaDescanso: "2 de enero de 2026", ubicacion: "Blanquizal" },
  { id: "1214716814", nombre: "POSSO JIMENEZ WILMAR ALEXANDER", cargo: "ENCARGADO(A)", fechaDescanso: "26 de diciembre y 02 de enero", ubicacion: "Blanquizal" },
  { id: "8152478", nombre: "ARANGO POSADA MARTIN FELIPE", cargo: "CONDUCTOR CAMIONETA", fechaDescanso: "26 de diciembre de 2025", ubicacion: "Conductores" },
  { id: "71336778", nombre: "TAPIAS MESA JHON JAIRO", cargo: "CONDUCTOR CAMIONETA", fechaDescanso: "26 de diciembre de 2025", ubicacion: "Conductores" },
  { id: "1152688798", nombre: "MANCO PATIÑO WALTHER ALEXANDER", cargo: "CONDUCTOR VOLQUETA", fechaDescanso: "26 de diciembre de 2025", ubicacion: "Conductores" },
  { id: "1143970100", nombre: "MURILLO DIAZ CRISTIAN ANDRES", cargo: "AYUDANTE", fechaDescanso: "2 de enero de 2026", ubicacion: "Blanquizal" },
  { id: "1000640375", nombre: "QUINTERO BARRIENTOS SANTIAGO", cargo: "AYUDANTE", fechaDescanso: "2 de enero de 2026", ubicacion: "Bodega" },
  { id: "98493816", nombre: "YEPES CLAVIJO JOHN BYRON", cargo: "CONDUCTOR VOLQUETA", fechaDescanso: "2 de enero de 2026", ubicacion: "Conductores" },
  { id: "1001359700", nombre: "PINEDA VILLA RICHAR ESTEBAN", cargo: "AYUDANTE", fechaDescanso: "26 de diciembre de 2025", ubicacion: "el cristo" },
  { id: "1007807801", nombre: "TUBERQUIA GOMEZ JOHN EDWIN", cargo: "AYUDANTE", fechaDescanso: "26 de diciembre de 2025", ubicacion: "el cristo" },
  { id: "1011391285", nombre: "ALZATE ACEVEDO SANTIAGO", cargo: "AYUDANTE", fechaDescanso: "26 de diciembre de 2025", ubicacion: "el cristo" },
  { id: "1035440186", nombre: "SANCHEZ GARCIA YONATAN ALEJANDRO", cargo: "CONDUCTOR CAMIONETA", fechaDescanso: "2 de enero de 2026", ubicacion: "Conductores" },
  { id: "1038334589", nombre: "ROLDAN LONDOÑO JUAN CAMILO", cargo: "CONDUCTOR CAMIONETA", fechaDescanso: "2 de enero de 2026", ubicacion: "Conductores" },
  { id: "4879288", nombre: "RUJANO GUASAMUCARO ELOY", cargo: "AYUDANTE", fechaDescanso: "2 de enero de 2026", ubicacion: "el cristo" },
  { id: "10186459", nombre: "RENDON BERNAL RIGOBERTO", cargo: "AYUDANTE ENTENDIDO", fechaDescanso: "2 de enero de 2026", ubicacion: "el cristo" },
  { id: "11038502", nombre: "LLORENTE LOPEZ ARLIS WILLIAM", cargo: "AYUDANTE", fechaDescanso: "2 de enero de 2026", ubicacion: "el cristo" },
  { id: "15513681", nombre: "ROMAÑA MORENO ELASIO", cargo: "AYUDANTE", fechaDescanso: "2 de enero de 2026", ubicacion: "el cristo" },
  { id: "71364666", nombre: "SANCHEZ SALDARRIAGA CHARLIE LEON", cargo: "AYUDANTE", fechaDescanso: "2 de enero de 2026", ubicacion: "el cristo" },
  { id: "1001024835", nombre: "ECHEVERRI ALBERTINO OMAR YESID", cargo: "AYUDANTE ENTENDIDO", fechaDescanso: "2 de enero de 2026", ubicacion: "el cristo" },
  { id: "1001598711", nombre: "NOBLE MUSLACO JOSE ALFONSO", cargo: "AYUDANTE", fechaDescanso: "2 de enero de 2026", ubicacion: "el cristo" },
  { id: "1039694936", nombre: "DIAZ RUA CATTERINE ALEXANDRA", cargo: "AYUDANTE", fechaDescanso: "2 de enero de 2026", ubicacion: "el cristo" },
  { id: "15648115", nombre: "HERNANDEZ PEREIRA DANIS DANIEL", cargo: "OFICIAL", fechaDescanso: "No sale", ubicacion: "el cristo" },
  { id: "71250389", nombre: "SIERRA CALLE IVAN ANTONIO", cargo: "AYUDANTE", fechaDescanso: "No sale", ubicacion: "el cristo" },
  { id: "71724282", nombre: "ESTRADA GUERRA VIVIAN DE JESUS", cargo: "OFICIAL", fechaDescanso: "No sale", ubicacion: "el cristo" },
  { id: "1017264216", nombre: "FLOREZ ALVAREZ JUAN DAVID", cargo: "AYUDANTE", fechaDescanso: "No sale", ubicacion: "el cristo" },
  { id: "1027950031", nombre: "MENA POTES LUIS FERNANDO", cargo: "AYUDANTE", fechaDescanso: "No sale", ubicacion: "el cristo" },
  { id: "1035862175", nombre: "CADAVID RIOS GABRIEL JAIME", cargo: "AYUDANTE", fechaDescanso: "No sale", ubicacion: "el cristo" },
  { id: "1073821032", nombre: "HERNANDEZ LOPEZ CARLOS ANDRES", cargo: "AYUDANTE", fechaDescanso: "No sale", ubicacion: "el cristo" },
  { id: "1070809003", nombre: "CARDENAS RAMOS ENDER JOSE", cargo: "AYUDANTE", fechaDescanso: "2 de enero de 2026", ubicacion: "el cristo" },
  { id: "8032823", nombre: "ARANGO ZAPATA JOSE DUCLIDES", cargo: "AYUDANTE", fechaDescanso: "Vacaciones", ubicacion: "Montaña 1" },
  { id: "1147935133", nombre: "GUTIERREZ MORENO NELSON ANDRES", cargo: "AYUDANTE", fechaDescanso: "2 de enero de 2026", ubicacion: "el cristo" },
  { id: "1099546554", nombre: "OSCAR ANDRADE URANGO", cargo: "OFICIAL", fechaDescanso: "2 de enero de 2026", ubicacion: "Micromedicion" },
  { id: "70164753", nombre: "ALDOVER ARISTIZABAL GIRALDO", cargo: "OFICIAL", fechaDescanso: "2 de enero de 2026", ubicacion: "Micromedicion" },
  { id: "1020447773", nombre: "HERNAN DARIO JARAMILLO PALACIOS", cargo: "AYUDANTE", fechaDescanso: "2 de enero de 2026", ubicacion: "Micromedicion" },
  { id: "1017193097", nombre: "JUAN CARLOS QUINTANA CANO", cargo: "AYUDANTE", fechaDescanso: "2 de enero de 2026", ubicacion: "Micromedicion" },
  { id: "1037478208", nombre: "DAIRO HERRERA GUARNE", cargo: "AYUDANTE", fechaDescanso: "2 de enero de 2026", ubicacion: "Micromedicion" },
  { id: "6069923", nombre: "YORBIS ALBERTO GONZALEZ GUILLEN", cargo: "AYUDANTE", fechaDescanso: "2 de enero de 2026", ubicacion: "Micromedicion" },
  { id: "1193229275", nombre: "RICARDO ANDRES MORALES ITURRIAGO", cargo: "AYUDANTE", fechaDescanso: "2 de enero de 2026", ubicacion: "Micromedicion" },
  { id: "1045078364", nombre: "DAIRO JOHANY ZULETA HENAO", cargo: "AYUDANTE ENTENDIDO", fechaDescanso: "2 de enero de 2026", ubicacion: "Micromedicion" },
  { id: "1017129924", nombre: "RAFAEL ANGEL GARCES GUTIERREZ", cargo: "AYUDANTE", fechaDescanso: "2 de enero de 2026", ubicacion: "Micromedicion" },
  { id: "6821212", nombre: "VILORIA SUAREZ JONAIKER DAVID", cargo: "AYUDANTE", fechaDescanso: "2 de enero de 2026", ubicacion: "Montaña 1" },
  { id: "8111773", nombre: "ARGEL BRU LIBARDO ANTONIO", cargo: "AYUDANTE", fechaDescanso: "2 de enero de 2026", ubicacion: "Montaña 1" },
  { id: "8154842", nombre: "RUA PEREZ OCTAVIO ALFONSO", cargo: "ENCARGADO(A)", fechaDescanso: "2 de enero de 2026", ubicacion: "Montaña 1" },
  { id: "8166555", nombre: "MEDRANO FLOREZ LUIS MIGUEL", cargo: "AYUDANTE", fechaDescanso: "2 de enero de 2026", ubicacion: "Montaña 1" },
  { id: "8439062", nombre: "ZAPATA SANCHEZ MIGUEL ANGEL", cargo: "AYUDANTE", fechaDescanso: "2 de enero de 2026", ubicacion: "Montaña 1" },
  { id: "11830474", nombre: "GUERRERO ROA LUIS GORGONIO", cargo: "AYUDANTE", fechaDescanso: "2 de enero de 2026", ubicacion: "Montaña 1" },
  { id: "98651613", nombre: "ACOSTA CASTRO EDILBERTO JOSE", cargo: "AYUDANTE", fechaDescanso: "Vacaciones", ubicacion: "Montaña 1" },
  { id: "14258284", nombre: "ARENAS VILLA JUAN DE DIOS", cargo: "AYUDANTE", fechaDescanso: "2 de enero de 2026", ubicacion: "Montaña 1" },
  { id: "15540013", nombre: "PARRA RUIZ GUSTAVO ADOLFO", cargo: "AYUDANTE", fechaDescanso: "2 de enero de 2026", ubicacion: "Montaña 1" },
  { id: "70002833", nombre: "FORONDA MARIN LUIS MEDARDO DE JESUS", cargo: "AYUDANTE", fechaDescanso: "2 de enero de 2026", ubicacion: "Montaña 1" },
  { id: "70141773", nombre: "ARDILA FRANKLIN ESTEBAN", cargo: "AYUDANTE", fechaDescanso: "2 de enero de 2026", ubicacion: "Montaña 1" },
  { id: "70581464", nombre: "BETANCUR CONCHA WILMAR ANTONIO", cargo: "AYUDANTE", fechaDescanso: "2 de enero de 2026", ubicacion: "Montaña 1" },
  { id: "70581786", nombre: "PEREZ ZABALA WALTER DE JESUS", cargo: "AYUDANTE", fechaDescanso: "2 de enero de 2026", ubicacion: "Montaña 1" },
  { id: "71370576", nombre: "JIMENEZ NORBEY DE JESUS", cargo: "AYUDANTE", fechaDescanso: "2 de enero de 2026", ubicacion: "Montaña 1" },
  { id: "71410665", nombre: "MAZO PEREZ JOAQUIN EMILIO", cargo: "AYUDANTE", fechaDescanso: "2 de enero de 2026", ubicacion: "Montaña 1" },
  { id: "71754329", nombre: "HIGUITA MISAS JORGE EMILIO", cargo: "OFICIAL", fechaDescanso: "2 de enero de 2026", ubicacion: "Montaña 1" },
  { id: "79208460", nombre: "GIL TALERO JOSE ELGAR", cargo: "AYUDANTE", fechaDescanso: "2 de enero de 2026", ubicacion: "Montaña 1" },
  { id: "98569984", nombre: "SEPULVEDA JIMENEZ WALTER EDISON", cargo: "OFICIAL", fechaDescanso: "2 de enero de 2026", ubicacion: "Montaña 1" },
  { id: "98709797", nombre: "PATIÑO LOPEZ WALTER JULIAN", cargo: "AYUDANTE", fechaDescanso: "2 de enero de 2026", ubicacion: "Montaña 1" },
  { id: "1001154066", nombre: "HERNANDEZ BENITEZ JAIDER FERNANDO", cargo: "AYUDANTE", fechaDescanso: "2 de enero de 2026", ubicacion: "Montaña 1" },
  { id: "1003970333", nombre: "PALACIOS PALACIOS JHON", cargo: "AYUDANTE", fechaDescanso: "2 de enero de 2026", ubicacion: "Montaña 1" },
  { id: "1035861267", nombre: "GONZALEZ ARIAS ADRIANA ISABEL", cargo: "AUXILIAR RESIDENTE", fechaDescanso: "26 de diciembre y 02 de enero", ubicacion: "Montaña 1" },
  { id: "1007531968", nombre: "ROBLEDO CORDOBA YARLEISON", cargo: "AYUDANTE", fechaDescanso: "2 de enero de 2026", ubicacion: "Montaña 1" },
  { id: "1017123467", nombre: "MORENO ORTIZ EDISON FERNANDO", cargo: "AYUDANTE", fechaDescanso: "2 de enero de 2026", ubicacion: "Montaña 1" },
  { id: "1017142648", nombre: "RIVERA MORENO MARCOS FIDEL", cargo: "AYUDANTE", fechaDescanso: "2 de enero de 2026", ubicacion: "Montaña 1" },
  { id: "1017193721", nombre: "GONZALEZ MARTINEZ NID BRAHIAN", cargo: "AYUDANTE", fechaDescanso: "2 de enero de 2026", ubicacion: "Montaña 1" },
  { id: "1017197900", nombre: "PALACIOS ORTIZ JORGE LUIS", cargo: "AYUDANTE", fechaDescanso: "2 de enero de 2026", ubicacion: "Montaña 1" },
  { id: "1017272193", nombre: "LOPERA MEJIA MICHAEL ESTIVEN", cargo: "AYUDANTE", fechaDescanso: "2 de enero de 2026", ubicacion: "Montaña 1" },
  { id: "1020429192", nombre: "ARBOLEDA LOPEZ DAIRON ALBERTO", cargo: "AYUDANTE", fechaDescanso: "2 de enero de 2026", ubicacion: "Montaña 1" },
  { id: "1025642713", nombre: "USUGA QUIROS SEBASTIAN", cargo: "AYUDANTE", fechaDescanso: "2 de enero de 2026", ubicacion: "Montaña 1" },
  { id: "1027942601", nombre: "VILORIA FUENTES YONIER", cargo: "AYUDANTE", fechaDescanso: "2 de enero de 2026", ubicacion: "Montaña 1" },
  { id: "1032326191", nombre: "GONZALEZ ZAMARRA WILMAR DE JESUS", cargo: "AYUDANTE", fechaDescanso: "2 de enero de 2026", ubicacion: "Montaña 1" },
  { id: "1033257900", nombre: "LONDOÑO GIRALDO JOSETH", cargo: "AYUDANTE", fechaDescanso: "2 de enero de 2026", ubicacion: "Montaña 1" },
  { id: "1036338389", nombre: "DIAZ OSPINA LUIS ALBERTO", cargo: "OFICIAL PEGADOR", fechaDescanso: "2 de enero de 2026", ubicacion: "Montaña 1" },
  { id: "8432069", nombre: "URREGO ALVAREZ NELSON UBEIMAR", cargo: "AYUDANTE", fechaDescanso: "26 de diciembre de 2025", ubicacion: "Montaña 2" },
  { id: "10178361", nombre: "MOSQUERA RENTERIA CARLOS ENRIQUE", cargo: "AYUDANTE", fechaDescanso: "26 de diciembre de 2025", ubicacion: "Montaña 2" },
  { id: "11804240", nombre: "RAMOS MURILLO ALEXANDER STEFAN", cargo: "AYUDANTE", fechaDescanso: "26 de diciembre de 2025", ubicacion: "Montaña 2" },
  { id: "71268303", nombre: "RUIZ LARREA JUAN PABLO", cargo: "AYUDANTE", fechaDescanso: "26 de diciembre de 2025", ubicacion: "Montaña 2" },
  { id: "71332317", nombre: "TUBERQUIA PALACIO JOHN FREDY", cargo: "OFICIAL", fechaDescanso: "26 de diciembre de 2025", ubicacion: "Montaña 2" },
  { id: "71725035", nombre: "RUIZ LOAIZA AUDI DE JESUS", cargo: "AYUDANTE", fechaDescanso: "26 de diciembre de 2025", ubicacion: "Montaña 2" },
  { id: "71731136", nombre: "ORTIZ CANO JOSE LUIS", cargo: "OFICIAL", fechaDescanso: "26 de diciembre de 2025", ubicacion: "Montaña 2" },
  { id: "98595317", nombre: "RESTREPO AGUDELO BERNARDO DE JESUS", cargo: "AYUDANTE", fechaDescanso: "26 de diciembre de 2025", ubicacion: "Montaña 2" },
  { id: "98664216", nombre: "HINCAPIE CEBALLOS JAVIER DE JESUS", cargo: "AYUDANTE", fechaDescanso: "26 de diciembre de 2025", ubicacion: "Montaña 2" },
  { id: "1000191961", nombre: "RIOS PALACIOS BLADER STIVEN", cargo: "AYUDANTE", fechaDescanso: "26 de diciembre de 2025", ubicacion: "Montaña 2" },
  { id: "1000192034", nombre: "PALACIOS MORENO FABIAN ANDRES", cargo: "AYUDANTE", fechaDescanso: "26 de diciembre de 2025", ubicacion: "Montaña 2" },
  { id: "1000195052", nombre: "ESTRADA RUIZ FRANCISCO JAVIER", cargo: "AYUDANTE", fechaDescanso: "26 de diciembre de 2025", ubicacion: "Montaña 2" },
  { id: "1000405459", nombre: "MOSQUERA MEDINA JHON ALEX", cargo: "AYUDANTE", fechaDescanso: "26 de diciembre de 2025", ubicacion: "Montaña 2" },
  { id: "1000894035", nombre: "AGUDELO CASTAÑO DANIEL", cargo: "AYUDANTE", fechaDescanso: "26 de diciembre de 2025", ubicacion: "Montaña 2" },
  { id: "1003645497", nombre: "VELASQUEZ DAVILA YEFRI DE JESUS", cargo: "AYUDANTE", fechaDescanso: "26 de diciembre de 2025", ubicacion: "Montaña 2" },
  { id: "1013340849", nombre: "MONTOYA MIRA DIEGO FERNANDO", cargo: "AYUDANTE", fechaDescanso: "26 de diciembre de 2025", ubicacion: "Montaña 2" },
  { id: "1015192175", nombre: "DUARTE SERNA ALEXANDER", cargo: "AYUDANTE", fechaDescanso: "26 de diciembre de 2025", ubicacion: "Montaña 2" },
  { id: "1017177282", nombre: "BEDOYA BORJA JONATHAN STIVEN", cargo: "AYUDANTE", fechaDescanso: "26 de diciembre de 2025", ubicacion: "Montaña 2" },
  { id: "1018236513", nombre: "ESCOBAR CORTES ANDRES FELIPE", cargo: "AYUDANTE", fechaDescanso: "26 de diciembre de 2025", ubicacion: "Montaña 2" },
  { id: "1021805955", nombre: "GUISAO NOREÑA KEVIN DANIEL", cargo: "AYUDANTE", fechaDescanso: "26 de diciembre de 2025", ubicacion: "Montaña 2" },
  { id: "1025763619", nombre: "TABORDA ACEVEDO JHOYNER DAVID", cargo: "AYUDANTE", fechaDescanso: "26 de diciembre de 2025", ubicacion: "Montaña 2" },
  { id: "1037671444", nombre: "ORTIZ TORRES YADIR STIVEN", cargo: "CONDUCTOR - OPERADOR DE MAQUINARIA", fechaDescanso: "26 de diciembre de 2025", ubicacion: "Montaña 2" },
  { id: "1066718772", nombre: "BARBERO FLOREZ EDUIN JOSE", cargo: "AYUDANTE", fechaDescanso: "26 de diciembre de 2025", ubicacion: "Montaña 2" },
  { id: "1086278625", nombre: "LASSO LOPEZ DAVID FERNEY", cargo: "AYUDANTE ENTENDIDO", fechaDescanso: "26 de diciembre de 2025", ubicacion: "Montaña 2" },
  { id: "1125474342", nombre: "CASTAÑEDA ZAPATA EDWIN DARIO", cargo: "AYUDANTE", fechaDescanso: "26 de diciembre de 2025", ubicacion: "Montaña 2" },
  { id: "1128419450", nombre: "PALOMEQUE BENITEZ EDGAR LUIS", cargo: "OFICIAL", fechaDescanso: "26 de diciembre de 2025", ubicacion: "Montaña 2" },
  { id: "1128426839", nombre: "SEPULVEDA GIRALDO JHOAN SEBASTIAN", cargo: "AYUDANTE", fechaDescanso: "26 de diciembre de 2025", ubicacion: "Montaña 2" },
  { id: "1152684523", nombre: "AGUIRRE URREGO LEANDRO ANTONIO", cargo: "AYUDANTE", fechaDescanso: "26 de diciembre de 2025", ubicacion: "Montaña 2" },
  { id: "1152695732", nombre: "PALACIO ZULUAGA JUAN CAMILO", cargo: "ENCARGADO(A)", fechaDescanso: "26 de diciembre de 2025", ubicacion: "Montaña 2" },
  { id: "1152697131", nombre: "GOMEZ PEREZ DIEGO ALONSO", cargo: "AYUDANTE", fechaDescanso: "26 de diciembre de 2025", ubicacion: "Montaña 2" },
  { id: "1192722135", nombre: "SUAREZ CANCHILA OSCAR DARIO", cargo: "AYUDANTE", fechaDescanso: "26 de diciembre de 2025", ubicacion: "Montaña 2" },
  { id: "1037600227", nombre: "RODRIGUEZ MORENO ANGEL AMERICO", cargo: "AYUDANTE", fechaDescanso: "2 de enero de 2026", ubicacion: "Montaña 1" },
  { id: "1037607566", nombre: "GIRALDO GARCIA YHONATAN", cargo: "AYUDANTE", fechaDescanso: "2 de enero de 2026", ubicacion: "Montaña 1" },
  { id: "1037613233", nombre: "LOPEZ HERRERA JONATHAN", cargo: "AYUDANTE", fechaDescanso: "2 de enero de 2026", ubicacion: "Montaña 1" },
  { id: "1037660512", nombre: "GUERRA USUGA SEBASTIAN DE JESUS", cargo: "AYUDANTE", fechaDescanso: "2 de enero de 2026", ubicacion: "Montaña 1" },
  { id: "1038815729", nombre: "CORDOBA CHALA DIEGO", cargo: "AYUDANTE", fechaDescanso: "2 de enero de 2026", ubicacion: "Montaña 1" },
  { id: "1045419890", nombre: "ESPINOSA MANCO LUIS MIGUEL", cargo: "AYUDANTE", fechaDescanso: "2 de enero de 2026", ubicacion: "Montaña 1" },
  { id: "1045425464", nombre: "CORREA CIRO DIOMER ALEXANDER", cargo: "AYUDANTE", fechaDescanso: "2 de enero de 2026", ubicacion: "Montaña 1" },
  { id: "1066601469", nombre: "AGAMEZ PADILLA JUAN PABLO", cargo: "AYUDANTE", fechaDescanso: "2 de enero de 2026", ubicacion: "Montaña 1" },
  { id: "1066728792", nombre: "ALVAREZ PINEDA ANGEL DANIEL", cargo: "AYUDANTE", fechaDescanso: "2 de enero de 2026", ubicacion: "Montaña 1" },
  { id: "1193413041", nombre: "GOEZ ZULETA DUVAN ARLEY", cargo: "AYUDANTE", fechaDescanso: "2 de enero de 2026", ubicacion: "Montaña 1" },
  { id: "1214716466", nombre: "RIOS RESTREPO JOAN ESTEBAN", cargo: "AYUDANTE", fechaDescanso: "2 de enero de 2026", ubicacion: "Montaña 1" },
  { id: "8129848", nombre: "MONTES SALDARRIAGA JOHN FREDY", cargo: "AYUDANTE", fechaDescanso: "2 de enero de 2026", ubicacion: "Montaña 3" },
  { id: "8417821", nombre: "PADIERNA SANCHEZ LEONEL", cargo: "AYUDANTE", fechaDescanso: "2 de enero de 2026", ubicacion: "Montaña 3" },
  { id: "15538384", nombre: "GOEZ GUISAO DAVINSON ANTONIO", cargo: "AYUDANTE", fechaDescanso: "2 de enero de 2026", ubicacion: "Montaña 3" },
  { id: "70352637", nombre: "PINEDA COSME EFRAIN", cargo: "ENCARGADO(A)", fechaDescanso: "2 de enero de 2026", ubicacion: "Montaña 3" },
  { id: "71214772", nombre: "ACEVEDO SANCHEZ EDWIN ORLANDO", cargo: "AUXILIAR ALMACENISTA", fechaDescanso: "2 de enero de 2026", ubicacion: "Montaña 3" },
  { id: "71370385", nombre: "MONROY GIRALDO JUAN BAUTISTA", cargo: "OFICIAL", fechaDescanso: "2 de enero de 2026", ubicacion: "Montaña 3" },
  { id: "1001021802", nombre: "CASTILLO CARDENAS CARLOS JAVIER", cargo: "AYUDANTE", fechaDescanso: "2 de enero de 2026", ubicacion: "Montaña 3" },
  { id: "1033651306", nombre: "GIRALDO ZAPATA JUAN FELIPE", cargo: "INGENIERO(A) DE DISEÑO A", fechaDescanso: "26 de diciembre de 2025", ubicacion: "Bodega" },
  { id: "1035230417", nombre: "CADAVID ORREGO LUISA FERNANDA", cargo: "GESTOR(A) COMERCIAL", fechaDescanso: "26 de diciembre de 2025", ubicacion: "Bodega" },
  { id: "1038766728", nombre: "JIMENEZ BETANCOURTH YORMAN ESTIBEN", cargo: "AYUDANTE", fechaDescanso: "26 de diciembre de 2025", ubicacion: "Bodega" },
  { id: "1128470225", nombre: "BURGOS ZAPATA JOHNNY ANDRES", cargo: "INGENIERO(A) RESIDENTE", fechaDescanso: "26 de diciembre de 2025", ubicacion: "Bodega" },
  { id: "1214729331", nombre: "GALLEGO ALZATE JENNIFER ANDREA", cargo: "GESTOR(A) SOCIAL", fechaDescanso: "26 de diciembre de 2025", ubicacion: "Bodega" },
  { id: "1001363044", nombre: "VALLE GUERRA DAVINSON", cargo: "AYUDANTE", fechaDescanso: "2 de enero de 2026", ubicacion: "Montaña 3" },
  { id: "1007649210", nombre: "GALINDO LOPEZ JEFFERSON ANDRES", cargo: "AYUDANTE", fechaDescanso: "2 de enero de 2026", ubicacion: "Montaña 3" },
  { id: "1013346104", nombre: "ALZATE HIGINIO UBER ANTONIO", cargo: "OFICIAL", fechaDescanso: "2 de enero de 2026", ubicacion: "Montaña 3" },
  { id: "1017160293", nombre: "GOMEZ CORREA GUSTAVO ADOLFO", cargo: "AYUDANTE", fechaDescanso: "2 de enero de 2026", ubicacion: "Montaña 3" },
  { id: "1021802238", nombre: "RESTREPO MEJIA NELSON ANDRES", cargo: "AYUDANTE", fechaDescanso: "2 de enero de 2026", ubicacion: "Montaña 3" },
  { id: "1023628162", nombre: "RAMIREZ CHAVARRIA ANDRES FELIPE", cargo: "AYUDANTE", fechaDescanso: "2 de enero de 2026", ubicacion: "Montaña 3" },
  { id: "1033426827", nombre: "MESA CARMONA YEFREY", cargo: "AYUDANTE", fechaDescanso: "2 de enero de 2026", ubicacion: "Montaña 3" },
  { id: "1036607296", nombre: "CARO ARBOLEDA JOHAN ALEXIS", cargo: "AYUDANTE", fechaDescanso: "2 de enero de 2026", ubicacion: "Montaña 3" },
  { id: "1045423085", nombre: "MANCO VALLE ALBA NUBIA", cargo: "AYUDANTE", fechaDescanso: "2 de enero de 2026", ubicacion: "Montaña 3" },
  { id: "1148141341", nombre: "MONTOYA GUTIERREZ CARLOS ANDRES", cargo: "AYUDANTE", fechaDescanso: "2 de enero de 2026", ubicacion: "Montaña 3" },
  { id: "1152713863", nombre: "MUÑOZ ZAPATA BRANDON STIVEN", cargo: "AYUDANTE", fechaDescanso: "2 de enero de 2026", ubicacion: "Montaña 3" },
  { id: "39215769", nombre: "CATAÑO ORREGO JULIET NATALIA", cargo: "COORDINADOR(A) SOCIAL", fechaDescanso: "2 de enero de 2026", ubicacion: "Bodega" },
  { id: "1152450270", nombre: "TEJADA CARDONA YESSICA PAOLA", cargo: "AUXILIAR ADMINISTRATIVA", fechaDescanso: "No sale", ubicacion: "Bodega" },
  { id: "8025998", nombre: "RAMIREZ HERNANDEZ JOHAN CAMILO", cargo: "AYUDANTE", fechaDescanso: "26 de diciembre de 2025", ubicacion: "Tanques" },
  { id: "10951069", nombre: "PAYARES GENEY LEONARDO DOMINGO", cargo: "OFICIAL", fechaDescanso: "26 de diciembre de 2025", ubicacion: "Tanques" },
  { id: "1017259646", nombre: "BERRIO GUARIN LEIDER", cargo: "OFICIAL PEGADOR", fechaDescanso: "26 de diciembre de 2025", ubicacion: "Tanques" },
  { id: "1020108031", nombre: "GOMEZ GIL JUAN PABLO", cargo: "AYUDANTE", fechaDescanso: "26 de diciembre de 2025", ubicacion: "Tanques" },
  { id: "1037624590", nombre: "MOSQUERA BENITEZ MARLEN YULIETH", cargo: "AYUDANTE", fechaDescanso: "26 de diciembre de 2025", ubicacion: "Tanques" },
  { id: "1214744620", nombre: "ROMAN BARRERA MARLON YESSID", cargo: "AYUDANTE", fechaDescanso: "26 de diciembre de 2025", ubicacion: "Tanques" },
  { id: "43865397", nombre: "RUIZ CRISTINA MARCELA", cargo: "AUXILIAR DE CAMPO", fechaDescanso: "2 de enero de 2026", ubicacion: "Bodega" },
  { id: "1000440827", nombre: "CADENA HENAO MARTHA YULITZA", cargo: "AUXILIAR DE CAMPO", fechaDescanso: "2 de enero de 2026", ubicacion: "Bodega" },
  { id: "1000897142", nombre: "URREGO CARVAJAL MARIA NATALIA", cargo: "AUXILIAR SST", fechaDescanso: "2 de enero de 2026", ubicacion: "Bodega" },
  { id: "1001587204", nombre: "LONDOÑO PELAEZ XIMENA", cargo: "AUXILIAR DE CAMPO", fechaDescanso: "2 de enero de 2026", ubicacion: "Bodega" },
  { id: "1001660904", nombre: "MANCO VARGAS BRAYAN ALEXIS", cargo: "AUXILIAR DE CAMPO", fechaDescanso: "2 de enero de 2026", ubicacion: "Bodega" },
  { id: "1017247150", nombre: "BOTERO RIVERA MARIANA", cargo: "INGENIERO(A) DE DISEÑO A", fechaDescanso: "2 de enero de 2026", ubicacion: "Bodega" },
  { id: "1035222407", nombre: "VANEGAS CADAVID YULI PAULINA", cargo: "AUXILIAR DE CAMPO", fechaDescanso: "2 de enero de 2026", ubicacion: "Bodega" },
  { id: "1037610338", nombre: "BEDOYA SUAREZ ANDRES FELIPE", cargo: "AUXILIAR DE CAMPO", fechaDescanso: "2 de enero de 2026", ubicacion: "Bodega" },
  { id: "1039025024", nombre: "ROMAN RESTREPO YUDY VANESA", cargo: "AUXILIAR AMBIENTAL", fechaDescanso: "2 de enero de 2026", ubicacion: "Bodega" },
  { id: "1114827951", nombre: "CAMAYO LOPEZ JHONATAN FERNEY", cargo: "GESTOR(A) SOCIAL", fechaDescanso: "2 de enero de 2026", ubicacion: "Bodega" },
  { id: "1037949514", nombre: "GARCIA MORALES PAOLA ANDREA", cargo: "AUXILIAR DE ACTAS", fechaDescanso: "26 de diciembre de 2025", ubicacion: "Verificacion" },
  { id: "70133760", nombre: "BURGOS GARCIA LUIS EDUARDO", cargo: "AUXILIAR DE ACTAS", fechaDescanso: "26 de diciembre de 2025", ubicacion: "Verificacion" },
  { id: "1128468559", nombre: "MEJIA LONDOÑO MARCELA", cargo: "INGENIERO(A) RESIDENTE", fechaDescanso: "2 de enero de 2026", ubicacion: "Bodega" },
  { id: "3556381", nombre: "VASQUEZ AREIZA ALEXANDER DE JESÚS", cargo: "OFICIAL PEGADOR", fechaDescanso: "2 de enero de 2026", ubicacion: "Tanques" },
  { id: "71337498", nombre: "MAYA RUA CARLOS ALBERTO", cargo: "OFICIAL", fechaDescanso: "2 de enero de 2026", ubicacion: "Tanques" },
  { id: "1001153209", nombre: "ARIAS CUBIDES JUAN ESTEBAN", cargo: "AYUDANTE", fechaDescanso: "2 de enero de 2026", ubicacion: "Tanques" },
  { id: "1017208486", nombre: "BOHORQUEZ LOPEZ EDWIN LEANDRO", cargo: "OFICIAL", fechaDescanso: "2 de enero de 2026", ubicacion: "Tanques" },
  { id: "1017256280", nombre: "ROMAN BARRERA MANUEL STIVEN", cargo: "AYUDANTE", fechaDescanso: "2 de enero de 2026", ubicacion: "Tanques" },
  { id: "1036659778", nombre: "CORDOBA PALACIOS CRISTIAN CAMILO", cargo: "AUXILIAR ALMACENISTA BODEGA", fechaDescanso: "2 de enero de 2026", ubicacion: "Tanques" },
  { id: "1039091077", nombre: "CARDEÑO MONTES OTONIEL DE JESUS", cargo: "AYUDANTE", fechaDescanso: "2 de enero de 2026", ubicacion: "Tanques" },
  { id: "1017128824", nombre: "JAIRO ALONSO GARCIA RODRIGUEZ", cargo: "AYUDANTE", fechaDescanso: "Vacaciones", ubicacion: "Micromedicion" },
  { id: "1035858538", nombre: "GALLON GARCIA KATTERIN LUCIA", cargo: "AUXILIAR DE ACTAS", fechaDescanso: "2 de enero de 2026", ubicacion: "Verificacion" },
  { id: "1037472641", nombre: "DAVISNEY HERRERA PEREZ", cargo: "OFICIAL", fechaDescanso: "26 de diciembre de 2025", ubicacion: "Micromedicion" },
  { id: "1000634659", nombre: "JUAN CAMILO LONDOÑO HENAO", cargo: "AYUDANTE", fechaDescanso: "26 de diciembre de 2025", ubicacion: "Micromedicion" },
  { id: "1037480112", nombre: "ENER LUIS HERRERA WUARNES", cargo: "AYUDANTE", fechaDescanso: "26 de diciembre de 2025", ubicacion: "Micromedicion" },
  { id: "1073825833", nombre: "GARCES MORALES JUAN JOSE", cargo: "VERIFICADOR (A)", fechaDescanso: "2 de enero de 2026", ubicacion: "Verificacion" },
  { id: "8418914", nombre: "SILVA PIEDRAHITA OSCAR URIEL", cargo: "AYUDANTE", fechaDescanso: "No sale", ubicacion: "Altos de la virgen" },
  { id: "98475876", nombre: "ALDANA VALLE FRANCISCO JAVIER", cargo: "AYUDANTE", fechaDescanso: "Vacaciones", ubicacion: "Blanquizal" },
  { id: "1000401781", nombre: "MONSALVE LONDOÑO DANILO", cargo: "AYUDANTE ENTENDIDO", fechaDescanso: "Incapacitado", ubicacion: "Blanquizal" },
  { id: "1128468809", nombre: "MOSQUERA LEUDO YEISON EMILIO", cargo: "AYUDANTE", fechaDescanso: "26 de diciembre de 2025", ubicacion: "Blanquizal" },
  { id: "1035868702", nombre: "VALDERRAMA ZULETA HENRY ALONSO", cargo: "AYUDANTE", fechaDescanso: "Vacaciones", ubicacion: "Blanquizal" },
  { id: "1020496205", nombre: "CORREA ESCALANTE JUAN PABLO", cargo: "AYUDANTE", fechaDescanso: "No sale", ubicacion: "Blanquizal" },
  { id: "98589480", nombre: "AGUDELO ORTIZ LUIS ALFONSO", cargo: "AYUDANTE", fechaDescanso: "Sin confirmar", ubicacion: "Bodega" },
  { id: "71777275", nombre: "CORREA PANIAGUA ALEXANDER", cargo: "DIRECTOR(A) DE PROYECTOS", fechaDescanso: "Vacaciones", ubicacion: "Bodega" },
  { id: "1214735760", nombre: "ECHAVARRIA BORJA DUVAN ALONSO", cargo: "AUXILIAR SST", fechaDescanso: "No sale", ubicacion: "Bodega" },
  { id: "1007928147", nombre: "HENAO GAVIRIA JUAN DAVID", cargo: "TOPOGRAFO (A)", fechaDescanso: "26 de diciembre y 02 de enero", ubicacion: "Bodega" },
  { id: "1128475121", nombre: "DURANGO ALZATE JUDIT PATRICIA", cargo: "VERIFICADOR (A)", fechaDescanso: "2 de enero de 2026", ubicacion: "Verificacion" },
  { id: "1020474681", nombre: "RUA ROMERO JHON EDISON", cargo: "AYUDANTE", fechaDescanso: "Incapacitado", ubicacion: "Bodega" },
  { id: "71877263", nombre: "SUAREZ PEREZ LUIS FERNANDO", cargo: "AYUDANTE", fechaDescanso: "Sin confirmar", ubicacion: "Bodega" },
  { id: "1152700033", nombre: "VAHOS GALVIS BRIAN ALEXIS", cargo: "AYUDANTE", fechaDescanso: "2 de enero de 2026", ubicacion: "Bodega" },
  { id: "1036396024", nombre: "GARCIA LOPEZ MILVIA HELENA", cargo: "GESTOR(A) AMBIENTAL", fechaDescanso: "No sale", ubicacion: "Bodega" },
  { id: "1128392013", nombre: "LOPEZ LOPEZ JOAN ESTEBAN", cargo: "OFICIAL ELECTRICISTA", fechaDescanso: "Sin confirmar", ubicacion: "CALDAS" },
  { id: "71616676", nombre: "MUÑOZ BRAN JORGE NELSON", cargo: "INGENIERO ELECTRICISTA", fechaDescanso: "Sin confirmar", ubicacion: "CALDAS" },
  { id: "1060586017", nombre: "RIOS AGUIRRE SANTIAGO ALEXIS", cargo: "AYUDANTE", fechaDescanso: "Sin confirmar", ubicacion: "CALDAS" },
  { id: "1030421389", nombre: "PEREA PEREA DANOBER", cargo: "AYUDANTE", fechaDescanso: "Vacaciones", ubicacion: "el cristo" },
  { id: "1064315454", nombre: "MESTRA BARRAGAN CARLOS ALFREDO", cargo: "ENCARGADO(A)", fechaDescanso: "No sale", ubicacion: "el cristo" },
  { id: "1064314290", nombre: "OVIEDO HERNANDEZ WILMER ANDRES", cargo: "ENCARGADO (A DE OBRAS CIVILES PROYECTOS)", fechaDescanso: "No sale", ubicacion: "Micromedicion" },
  { id: "1077462884", nombre: "SERNA MUÑOZ LUIS ALBERTO", cargo: "AYUDANTE", fechaDescanso: "Sin confirmar", ubicacion: "Tanques" },
];
